#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# ingress
###################################################################################################
{{- $svcversion := .Chart.AppVersion | replace "." "" }}
{{- $appversion := .Chart.AppVersion }}
{{- $defaultversionedpath := printf "/%s/" $appversion }}
{{- $relname := .Release.Name }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $relname }}-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "appgw-ssl-certificate"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/api/deliveries"
    # TODO: modify delivery containers to start listening https instead (dont forget
    # probes as they override the appgw probes cfg). Then uncomment the following
    # annotations to have e2e TLS: https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1048
    # appgw.ingress.kubernetes.io/ssl-redirect: "false"
    # appgw.ingress.kubernetes.io/backend-protocol: "https"
    # appgw.ingress.kubernetes.io/backend-hostname: "shipping.aks-agic.fabrikam.com"
    # appgw.ingress.kubernetes.io/hostname-extension: "*.aks-agic.fabrikam.com"
    # appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "root-cert-wildcard-aks-ingress-fabrikam"
spec:
  ingressClassName: azure-application-gateway
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  - hosts:
    - {{ .name }}
    secretName: {{ $relname }}-{{ .tlsSecretName }}
  {{- end }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      {{- if .path }}
      - path: {{ printf "%s/%s/" .path $appversion }}api/deliveries
        pathType: Prefix
      {{- else }}
      - path: {{ $defaultversionedpath }}api/deliveries
        pathType: Prefix
      {{- end }}
        backend:
          service:
            name: "{{ .serviceName }}-{{ $svcversion }}"
            port:
              name: http
  {{ end }}
